{{- if .Values.rbac.clusterRole.restApiFixedAuthViewer.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.clusteRole.restApiFixedAuthViewer" . }}
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
    - verbs:
        - get
        - list
        - watch
      apiGroups:
        - streaming.sneaksanddata.com
      resources:
        - api-fas
{{- end }}
