{{- if .Values.rbac.clusterRole.restApiPagedDynamicAuthViewer.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.clusteRole.restApiPagedDynamicAuthViewer" . }}
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - streaming.sneaksanddata.com
    resources:
      - api-pdas
      - api-pdas/status
{{- end }}
