{{- if and .Values.rbac.clusterRole.restApiFixedAuthViewer.create .Values.rbac.clusterRoleBindings.create -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "app.serviceAccountName" . }}-rest-api-fa-viewer
subjects:
  - kind: ServiceAccount
    name: {{ template "app.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "app.clusteRole.restApiFixedAuthViewer" . }}
  
{{- end }}
