{{- if .Values.rbac.clusterRole.restApiPagedDynamicAuthEditor.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.clusteRole.restApiPagedDynamicAuthEditor" . }}
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
    - verbs:
        - create
        - update
        - patch
        - delete
      apiGroups:
        - streaming.sneaksanddata.com
      resources:
        - api-pdas
        - api-pdas/status
{{- end }}
