apiVersion: streaming.sneaksanddata.com/v1
kind: StreamClass
metadata:
  name: {{ template "app.name" . }}-paged-fa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamclass.labels" $ | nindent 4 }}
  {{- if .Values.additionalAnnotations }}
  annotations:
    {{- with .Values.additionalAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  apiGroupRef: streaming.sneaksanddata.com
  kindRef: RestApiPagedFixedAuth
  apiVersion: v1beta1
  pluralName: api-pfas
  secretRefs:
    - credentialSecretRef
